### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by yudhatand** [MhmdAwad/Superest#4]
Dear Mohamed Awad,

I would love to try your app so I can learn more about Android Development. But the problem is I can’t login to the app at all. If I try login using phone number, it will crash the app. And if I try login using Google Account, nothing is happening and it gives me an error message. Can you help me? It will be much appreciated. Thank You.

Sincerely,
Wira Yudha

<img width="1440" alt="Screenshot 2023-05-21 at 2 19 45 AM" src="https://github.com/MhmdAwad/Superest/assets/95838550/e834971e-7f44-4f36-a872-e4011f186432">

<img width="1440" alt="Screenshot 2023-05-21 at 2 14 05 AM" src="https://github.com/MhmdAwad/Superest/assets/95838550/5f77657f-7aa6-498f-91c1-4a9f1f37ccba">

**Comment by MhmdAwad** [comment]
Hello W. Yudha Tandungan,

Thank you for your email.

Regarding the login issue I've pushed a new commit on the master branch,
Kindly pull it and try to log in with phone auth but make sure you run the
app with release variants not debug one.
For some reason, if it does not work try to use this number +11234567899
and the otp is 123123.

I hope this helps.

Thank you,



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/21/23,
05:10:04 PM
