### ISSUE TITLE
/

### ISSUE THREAD

**Issue by megaacheyounes** [MhmdAwad/Superest#6]
It appears that the app connects to a local GraphQl server

```kotlin
@Singleton
    @Provides
    fun provideApolloClient(okHttpClient: OkHttpClient): ApolloClient {
        return ApolloClient.builder()
            .serverUrl("http://192.168.1.7:5000/") //<--
            .okHttpClient(okHttpClient)
            .build()
    }
```

Will you be able to publish your server code, or provide it here ?

Thank you

**Comment by MhmdAwad** [comment]
Hello,

Could you please let me know in which class you found this function? I didn't find this function!

Thanks,

**Comment by megaacheyounes** [comment]
Apologies, wrong repo
